name: craftyfashions_webapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  fluttertoast: ^8.0.1-nullsafety.0
  font_awesome_flutter: ^8.11.0
  carousel_slider: ^3.0.0
  lottie: ^1.0.1
  like_button: ^1.0.4
  google_fonts: ^1.1.2
  http_parser: ^3.0.9
  custom_radio_grouped_button: ^1.0.6+1
  http: ^0.12.2
  progress_dialog: ^1.2.4
  empty_widget: ^0.0.1
  razorpay_flutter: ^1.1.1
  provider: ^5.0.0
  shared_preferences: ^2.0.4
  dio: ^3.0.9
  material_dialogs: ^0.1.4
  pull_to_refresh: ^1.6.3
  flutter_spinkit: ^4.1.2
  connectivity: ^3.0.3
  data_connection_checker: ^0.3.4
  url_launcher: ^6.0.3
  photo_view: ^0.11.1
  change_app_package_name: ^0.1.2
  fragment_navigate: ^1.1.0+2
  email_validator: ^2.0.1
  cached_network_image: ^2.5.0
  flare_splash_screen: ^2.0.1+2
  webviewx: ^0.0.4
  sizer: ^2.0.13
#  easy_web_view: ^1.3.1
#  easy_web_view: ^1.3.0
  badges: ^2.0.1
  flutter_icons: ^1.1.0
  cashfree_pg: 1.2.2+16
  substring_highlight: ^1.0.33
  clipboard: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/404.png
    - assets/images/doodleWall.jpg
    - assets/images/crafty.png
    - assets/images/settings.png
    - assets/images/error.webp
    - assets/images/warning.webp
    - assets/images/men.jpg
    - assets/images/logo.png
    - assets/images/women.jpg
    - assets/images/payment.jpg
    - assets/images/user.png
    - assets/images/kk.jpg
    - assets/images/mask.webp
    - assets/images/shopping-cart.webp
    - assets/images/favourite.webp
    - assets/images/nointernet.png
    - assets/raw/safe.json
    - assets/raw/shoppingcart.json
    - assets/raw/like.json
    - assets/raw/failed.json
    - assets/raw/successful.json
    - assets/raw/loading.json
    - assets/Policy/payment.html
    - assets/Policy/RETURN AND REFUND POLICY.htm
    - assets/Policy/RETURN AND REFUND POLICY_files/colorschememapping.xml
    - assets/Policy/RETURN AND REFUND POLICY_files/filelist.xml
    - assets/Policy/RETURN AND REFUND POLICY_files/themedata.thmx
#    - assets/Policy/RETURN AND REFUND POLICY_files/cashfree.html
    - assets/Policy/index.html
    - assets/Policy/style.css

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: EBGaramond
      fonts:
        - asset: assets/Fonts/EBGaramond-Regular.ttf
        - asset: assets/Fonts/EBGaramond-Medium.ttf
        - asset: assets/Fonts/EBGaramond-Bold.ttf
    - family: Somana
      fonts:
        - asset: assets/Fonts/Sumana-Bold.ttf
        - asset: assets/Fonts/Sumana-Regular.ttf
    - family: Beyond
      fonts:
        - asset: assets/Fonts/beyond_the_mountains.ttf
    - family: Halyard
      fonts:
        - asset: assets/Fonts/Halyard Text Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
